var Cbleep= new Audio()
	Cbleep.src = "keysounds/C.wav";
	var Dbleep= new Audio()
	Dbleep.src = "keysounds/D.wav";
	var Ebleep= new Audio()
	Ebleep.src = "keysounds/E.wav";
	var Fbleep= new Audio()
	Fbleep.src = "keysounds/F.wav";
	var Gbleep= new Audio()
	Gbleep.src = "keysounds/G.wav";
	var Ableep= new Audio()
	Ableep.src = "keysounds/A.wav";
	var Bbleep= new Audio()
	Bbleep.src = "keysounds/B.wav";
	var C1bleep= new Audio()
	C1bleep.src = "keysounds/C1.wav";
	var D1bleep= new Audio()
	D1bleep.src = "keysounds/D1.wav";
	var E1bleep= new Audio()
	E1bleep.src = "keysounds/E1.wav";
	var F1bleep= new Audio()
	F1bleep.src = "keysounds/F1.wav";
	var Csbleep= new Audio()
	Csbleep.src = "keysounds/C_s.wav";
	var Dsbleep= new Audio()
	Dsbleep.src = "keysounds/D_s.wav";
	var Fsbleep= new Audio()
	Fsbleep.src = "keysounds/F_s.wav";
	var Gsbleep= new Audio()
	Gsbleep.src = "keysounds/G_s.wav";
	var Bbbleep= new Audio()
	Bbbleep.src = "keysounds/Bb.wav";
	var Cs1bleep= new Audio()
	Cs1bleep.src = "keysounds/C_s1.wav";
	var Ds1bleep= new Audio()
	Ds1bleep.src = "keysounds/D_s1.wav";